import Head from "next/head"
import styles from "/styles/Home.module.css"
import { ChatLog } from "@/components/chat-log"
import { Header } from "@/components/header/header"
import { Footer } from "@/components/footer/footer"
import { createContext } from "react"
import { useSelector } from "react-redux"

export const PostList = createContext()

export default function Home() {
  const postList = useSelector((state) => state.posts.value)

  return (
    <>
      <PostList.Provider value={postList}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.main}>
          <ChatLog />
        </main>
        <Footer />
      </PostList.Provider>
    </>
  )
}
