import Head from "next/head"
import styles from "/styles/Home.module.css"
import { ChatLog } from "@/components/chat-log"
import { Header } from "@/components/header/header"
import { Footer } from "@/components/footer/footer"

/**
 * UNIX TIME => hh:mm
 **/
const getStrTime = (time) => {
  let t = new Date(time)
  return `${t.getHours()}`.padStart(2, "0") + ":" + `${t.getMinutes()}`.padStart(2, "0")
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <ChatLog />
      </main>
      <Footer />
    </>
  )
}
