import Head from "next/head"
import styles from "/styles/Home.module.css"
import { useSelector } from "react-redux"
import { MessageInput } from "@/components/message-input"

/**
 * UNIX TIME => hh:mm
 **/
const getStrTime = (time) => {
  let t = new Date(time)
  return `${t.getHours()}`.padStart(2, "0") + ":" + `${t.getMinutes()}`.padStart(2, "0")
}

export default function Home() {
  const postList = useSelector((state) => state.posts.value)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>qaqaチャット</h2>
        </div>
        <div>
          {postList.map((post) => (
            <div key={post.id} className="post">
              <h1 className="postName">{post.name}</h1>
              <h1 className="postContent">{post.content}</h1>
            </div>
          ))}
        </div>
        <div>
          <MessageInput />
        </div>
      </main>
    </>
  )
}
